import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { build } from "esbuild";
const cwd = new URL("../", import.meta.url);
const bundled = await build({
  entryPoints: [new URL("../browser/toolbar.tsx", import.meta.url).pathname],
  bundle: true,
  write: false,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  legalComments: "inline",
});
const css = execFileSync(
  new URL("../node_modules/.bin/tailwindcss", import.meta.url).pathname,
  ["-i", "browser/toolbar.css", "--minify"],
  { cwd, encoding: "utf8" },
);
const reviewBundle = await build({
  entryPoints: [new URL("../browser/review.tsx", import.meta.url).pathname],
  bundle: true,
  write: false,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
});
const reviewCss = execFileSync(
  new URL("../node_modules/.bin/tailwindcss", import.meta.url).pathname,
  ["-i", "browser/review.css", "--minify"],
  { cwd, encoding: "utf8" },
);
const files = {};
for (const name of [
  "toolbar.js",
  "toolbar.css",
  "admin.js",
  "admin.css",
  "review.js",
  "review.css",
]) {
  const body =
    name === "review.js"
      ? reviewBundle.outputFiles[0].text
      : name === "review.css"
        ? reviewCss
        : name === "toolbar.js"
          ? bundled.outputFiles[0].text
          : name === "toolbar.css"
            ? css
            : await readFile(new URL(`../browser/${name}`, import.meta.url), "utf8");
  const digest = createHash("sha256").update(body).digest("hex").slice(0, 20);
  files[name] = {
    path: `${digest}/${name}`,
    body,
    type: name.endsWith(".css") ? "text/css; charset=utf-8" : "text/javascript; charset=utf-8",
  };
}
await writeFile(
  new URL("../src/assets.generated.ts", import.meta.url),
  `// Generated by our package build; browser assets are opaque strings to host builds.\nexport const assets: Record<"toolbar.js" | "toolbar.css" | "admin.js" | "admin.css" | "review.js" | "review.css", {path:string;body:string;type:string}> = ${JSON.stringify(files)};\n`,
);
