import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { basename } from "node:path";
import { execFileSync } from "node:child_process";
import { build } from "esbuild";
const cwd = new URL("../", import.meta.url);
// Shared runtime once; Markdown parsing loads only when the editor opens.
const bundle = await build({
  absWorkingDir: cwd.pathname,
  entryPoints: { toolbar: "browser/toolbar.tsx", review: "browser/review.tsx" },
  outdir: "bundle",
  entryNames: "[name]-[hash]",
  chunkNames: "chunk-[hash]",
  bundle: true,
  splitting: true,
  write: false,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  legalComments: "inline",
  metafile: true,
});
const files = {};
for (const output of bundle.outputFiles) {
  const name = basename(output.path);
  const key = name.startsWith("toolbar-")
    ? "toolbar.js"
    : name.startsWith("review-")
      ? "review.js"
      : name;
  files[key] = { path: `js/${name}`, body: output.text, type: "text/javascript; charset=utf-8" };
}
for (const name of ["toolbar.css", "review.css", "admin.js", "admin.css"]) {
  const body =
    name === "toolbar.css" || name === "review.css"
      ? execFileSync(
          new URL("../node_modules/.bin/tailwindcss", import.meta.url).pathname,
          ["-i", `browser/${name}`, "--minify"],
          { cwd, encoding: "utf8" },
        )
      : await readFile(new URL(`../browser/${name}`, import.meta.url), "utf8");
  const digest = createHash("sha256").update(body).digest("hex").slice(0, 20);
  files[name] = {
    path: `${digest}/${name}`,
    body,
    type: name.endsWith(".css") ? "text/css; charset=utf-8" : "text/javascript; charset=utf-8",
  };
}
await writeFile(
  new URL("../src/assets.generated.ts", import.meta.url),
  `// Generated by our package build; browser assets are opaque strings to host builds.\nexport const assets: Record<string, {path:string;body:string;type:string}> = ${JSON.stringify(files)};\n`,
);
